[package]
name = "snarkos"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "A decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
    "algorithms",
    "benchmarks",
    "consensus",
    "console",
    "curves",
    "dpc",
    "errors",
    "gadgets",
    "models",
    "network",
    "objects",
    "parameters",
    "posw",
    "profiler",
    "rpc",
    "storage",
    "testing",
    "toolkit",
    "utilities"
]

[lib]
name = "snarkos"
path = "snarkOS/lib.rs"

[[bin]]
name = "snarkos"
path = "snarkOS/main.rs"

[dependencies]
snarkos-consensus = { path = "./consensus", version = "0.8.0" }
snarkos-dpc = { path = "./dpc", version = "0.8.0" }
snarkos-errors = { path = "./errors", version = "0.8.0" }
snarkos-network = { path = "network", version = "0.8.0" }
snarkos-objects = { path = "objects", version = "0.8.0" }
snarkos-posw = { path = "./posw", version = "0.8.0" }
snarkos-rpc = { path = "./rpc", version = "0.8.0" }
snarkos-storage = { path = "storage", version = "0.8.0" }
snarkos-utilities = { path = "./utilities", version = "0.8.0" }

clap = { version = "2.33.1" }
colored = { version = "2.0" }
dirs = { version = "3.0.1" }
env_logger = { version = "0.7.1" }
hex = { version = "0.4.1" }
log = { version = "0.4.11" }
rand = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2.13", features = ["full"] }

[dev-dependencies]
rusty-hook = { version = "0.11.2" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3 # necessary for DPC testing
lto = "thin"
incremental = true
debug-assertions = true
debug = true
