version: "3.5"

services:
  bootnode:
    container_name: snarkos-bootnode
    image: aleohq/snarkos:staging-latest
    volumes:
      - snarkos-bootn-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14131 --rpc-port 13031 --is-bootnode --ip 172.22.0.11 --connect 172.22.0.11:14131"]
    ports:
      - 13031:13031
      - 14131:14131
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          memory: 96M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      aleo_devnet:
        ipv4_address: 172.22.0.11

  client:
    container_name: snarkos-client
    image: aleohq/snarkos:staging-latest
    volumes:
      - snarkos-client-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14132 --rpc-port 13032 --ip 172.22.0.12 --connect 172.22.0.11:14131"]
    ports:
      - 13032:13032
      - 14132:14132
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          memory: 96M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      aleo_devnet:
        ipv4_address: 172.22.0.12

  miner:
    container_name: snarkos-miner
    image: aleohq/snarkos:staging-latest
    volumes:
      - snarkos-miner-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14133 --rpc-port 13033 --is-miner --miner-address ${ALEO_ADDRESS} --ip 172.22.0.13 --connect 172.22.0.11:14131"]
    ports:
      - 13033:13033
      - 14133:14133
    deploy:
      resources:
        limits:
          cpus: 3.00
          memory: 7168M
        reservations:
          memory: 4096M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      aleo_devnet:
        ipv4_address: 172.22.0.13

networks:
  aleo_devnet:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"

volumes:
  snarkos-bootn-vol:
  snarkos-miner-vol:
  snarkos-client-vol:
