pre-release-commit-message = "chore({{crate_name}}): Release {{version}}"
pre-release-replacements = [
  { file = "README.md", search = "snarkOS [a-z0-9\\.-]+", replace = "snarkOS {{version}}", min = 0 } ,
]
post-release-commit-message = "Released new version"
consolidate-commits = true
disable-tag = true
