[package]
name = "snarkos-utilities"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Utilities for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
rand = { version = "0.7", default-features = false }

[dev-dependencies]
rand_xorshift = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = []
