[package]
name = "snarkos-toolkit"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "A developer toolkit for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "account"
harness = false

[dependencies]
snarkos-dpc = { path = "../dpc", version = "0.8.0", default-features = false }
snarkos-errors = { path = "../errors", version = "0.8.0", default-features = false }
snarkos-objects = { path = "../objects", version = "0.8.0", default-features = false }
snarkos-utilities = { path = "../utilities", version = "0.8.0" }

rand = { version = "0.7", default-features = false, features = ["wasm-bindgen"] }
thiserror = { version = "1.0" }
wasm-bindgen = { version = "0.2.67" }

[dev-dependencies]
criterion = { version = "0.3.1" }
rand_chacha = { version = "0.2", default-features = false }
wasm-bindgen-test = { version = "0.3.15" }
