[package]
name = "snarkos-toolkit"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "A developer toolkit for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies]
snarkos-dpc = { path = "../dpc", version = "1.1.4", default-features = false }
snarkos-errors = { path = "../errors", version = "1.1.4", default-features = false }
snarkos-models = { path = "../models", version = "1.1.4", default-features = false }
snarkos-objects = { path = "../objects", version = "1.1.4", default-features = false }
snarkos-utilities = { path = "../utilities", version = "1.1.4"}

hex = { version = "0.4.2" }
rand = { version = "0.7", default-features = false, features = ["wasm-bindgen"] }
thiserror = { version = "1.0" }
wasm-bindgen = { version = "0.2.68" }

[dev-dependencies]
criterion = { version = "0.3.1" }
rand_chacha = { version = "0.2", default-features = false }
wasm-bindgen-test = { version = "0.3.18" }
