[package]
name = "snarkos-parameters"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Parameters for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-errors = { path = "../errors", version = "0.8.0" }
snarkos-models = { path = "../models", version = "0.8.0" }

curl = { version = "0.4.29" }

[dev-dependencies]
snarkos-algorithms = { path = "../algorithms", version = "0.8.0" }
snarkos-dpc = { path = "../dpc", version = "0.8.0" }
snarkos-utilities = { path = "../utilities", version = "0.8.0" }

rand = { version = "0.7" }
