[package]
name = "snarkos-storage"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Storage for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "0.8.0" }
snarkos-errors = { path = "../errors", version = "0.8.0" }
snarkos-models = { path = "../models", version = "0.8.0" }
snarkos-objects = { path = "../objects", version = "0.8.0" }
snarkos-utilities = { path = "../utilities", version = "0.8.0" }

bincode = { version = "1.2.0" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.10.0" }
rand = { version = "0.7" }
rocksdb = { version = "0.13.0" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
snarkos-curves = { path = "../curves", version = "0.8.0" }
