[package]
name = "snarkos-storage"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.0.0" }
snarkos-errors = { path = "../errors", version = "1.0.0" }
snarkos-models = { path = "../models", version = "1.0.0" }
snarkos-objects = { path = "../objects", version = "1.0.0" }
snarkos-parameters = { path = "../parameters", version = "1.0.0" }
snarkos-utilities = { path = "../utilities", version = "1.0.0" }

bincode = { version = "1.3.1" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.0" }
rand = { version = "0.7" }
rocksdb = { version = "0.13.0" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
snarkos-consensus = { path = "../consensus" }
snarkos-curves = { path = "../curves" }
snarkos-testing = { path = "../testing" }
