[package]
name = "snarkos-errors"
version = "0.8.0"
authors = ["Michael Beller", "Collin Chin", "Raymond Chu", "Matthew Green", "Ian Miers", "Howard Wu"]
description = "Errors for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
base58 = { version = "0.1" }
bincode = { version = "1.2.0" }
failure = { version = "0.1.7" }
hex = { version = "0.4.2" }
jsonrpc-core = { version = "14.0.5" }
rocksdb = { version = "0.13.0" }
secp256k1 = { version = "0.15.5" }
wagyu-model = { version = "0.6.1" }
